# Generated by Django 4.2.8 on 2023-12-22 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newspaper_agency", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspaper",
            name="content",
            field=models.TextField(default="Blanked news, all very good."),
        ),
        migrations.AddField(
            model_name="newspaper",
            name="published_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
